apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: demo-wsgi
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-ccordoui-tenant/demo-wsgi/demo-wsgi@sha256:709e6b27c4ab83efb15566dddf74923c82b745e93f2287d15895b56b9478e080
        name: my-python
        resources: {}
status: {}
