apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: demo-wsgi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-ccordoui-tenant/demo-wsgi/demo-wsgi@sha256:f5ee0b5eabcdf11fa329354e5ba08684ae1b63e74aa0357ad711f8a551bc4c27
        name: my-python
        resources: {}
status: {}
