apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: demo-wsgi
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-ccordoui-tenant/demo-wsgi/demo-wsgi@sha256:1c7e9b7793ac30bff9fcd1e79702098544407503bfddd86523f398dae7b13ee5
        name: my-python
        resources: {}
status: {}
