apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-wsgi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-wsgi
    app.kubernetes.io/part-of: demo-wsgi
  name: demo-wsgiwvkc
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: demo-wsgi
    weight: null
status: {}
