apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-wsgi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-wsgi
    app.kubernetes.io/part-of: demo-wsgi
  name: demo-wsgi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: demo-wsgi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: demo-wsgi
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-ccordoui-tenant/demo-wsgi/demo-wsgi@sha256:f5ee0b5eabcdf11fa329354e5ba08684ae1b63e74aa0357ad711f8a551bc4c27
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
status: {}
