apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-wsgi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-wsgi
    app.kubernetes.io/part-of: demo-wsgi
  name: demo-wsgi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: demo-wsgi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: demo-wsgi
    spec:
      containers:
      - env:
        - name: HOST
          value: 0.0.0.0
        image: quay.io/redhat-user-workloads/rh-ee-ccordoui-tenant/demo-wsgi/demo-wsgi@sha256:0ff6b894eed47006bced1739969fafbf8d24f3e77f06f026db2f579ca8150326
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
status: {}
