apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-wsgi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-wsgi
    app.kubernetes.io/part-of: demo-wsgi
  name: demo-wsgi
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app.kubernetes.io/instance: demo-wsgi
status:
  loadBalancer: {}
